apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: robusta
  labels:
    app: alertmanager-standalone
    alertmanager: standalone
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: robusta
    receivers:
    - name: robusta
      webhook_configs:
      - url: http://robusta-runner.robusta.svc.cluster.local/api/alerts
        send_resolved: true
