apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: robusta
  labels:
    app: alertmanager-standalone
    alertmanager: standalone
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: robusta
    receivers:
    - name: robusta
      webhook_configs:
      - url: http://robusta-forwarder.robusta.svc.cluster.local:3030/
        send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-standalone
  namespace: robusta
  labels:
    app: alertmanager-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-standalone
  template:
    metadata:
      labels:
        app: alertmanager-standalone
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.26.0
        imagePullPolicy: IfNotPresent
        args:
          - --config.file=/etc/alertmanager/alertmanager.yml
          - --storage.path=/alertmanager
        ports:
          - name: web
            containerPort: 9093
        volumeMounts:
          - name: config
            mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: robusta
  labels:
    app: alertmanager-standalone
spec:
  selector:
    app: alertmanager-standalone
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
