clusterName: kind
customPlaybooks:
- actions:
  - create_finding:
      aggregation_key: PromAlert-$alertname-$fingerprint
      severity: HIGH
      title: 'Prometheus Alert: $alert_name ($fingerprint)'
  name: ForwardAllPromAlerts
  sinks:
  - hub_webhook
  triggers:
  - on_prometheus_alert: {}
- actions:
  - create_finding:
      aggregation_key: ImgPullBackoff-$namespace-$name
      severity: HIGH
      title: 'ImagePullBackOff: $name ($namespace)'
  name: ImagePullBackoffToHub
  sinks:
  - hub_webhook
  triggers:
  - on_image_pull_backoff:
      rate_limit: 5
- actions:
  - create_finding:
      aggregation_key: K8sWarn-$namespace-$name-$reason
      description: $message
      severity: HIGH
      title: 'K8s Warning: $name ($namespace)'
  name: K8sWarnFailedImagePullToHub
  sinks:
  - hub_webhook
  triggers:
  - on_kubernetes_warning_event_create:
      include:
      - Failed
      - BackOff
      rate_limit: 5
fullnameOverride: robusta
nameOverride: robusta
playbookRepos: {}
playbooksPersistentVolume: true
prometheusStack:
  enabled: true
runner:
  log_level: DEBUG
sinksConfig:
- webhook_sink:
    headers:
      Authorization: Bearer dev-api-key-123
      X-API-Key: dev-api-key-123
      X-Robusta-Cluster-ID: kind
    name: hub_webhook
    url: http://hub-proxy.robusta.svc.cluster.local:8080/api/v1/ingest/robusta-webhook

